
name: PyTest

on:
  pull_request:
    branches: [ "dev", "master" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pytest:
    name: Run PyTest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        pip install pytest
        pip install .

    - name: Run pytest
      run: |
        pytest