
name: PyType

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev", "master" ]

permissions:
  contents: read

jobs:
  pytype:
    name: Run PyType
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytype pytest
        pip install .
    - name: Run pytype
      run: |
        pytype
    - name: Test with pytest
      run: |
        pytest
